# This is a github action to get the amount of files in /questions and then update the filecount in readme.md
name: File Count
on:
  push:
    branches:
      - master
jobs:
  filecount:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get file count
        id: filecount
        run: |
          echo "::set-output name=count::$(find questions -type f | wc -l)"
      - name: Update readme.md
        # the 8th line of readme.md should look like this: "Code Questions is a collection of over {filecount} questions that have been asked about code on Stack Overflow and other sites. The questions are currently not grouped. They accessable from /questions"
        run: |
          sed -i "8s/.*/Code Questions is a collection of over ${{ steps.filecount.outputs.count }} questions that have been asked about code on Stack Overflow and other sites. The questions are currently not grouped. They accessable from \/questions/" README.md
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add readme.md
          git commit -m "Update file count in readme.md"
          git push